import { useEffect, useState } from 'react';

export type SupportedLanguage = 'en' | 'es' | 'pt' | 'fr' | 'de' | 'it';

export interface LanguageOption {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  flag: string;
}

function interpolate(template: string, params?: TranslationParams): string {
  if (!params) return template;

  return template.replace(/\{\{\s*(\w+)\s*\}\}/g, (_match, key) => {
    const value = params[key];
    return value === undefined ? '' : String(value);
  });
}

export function translate(language: SupportedLanguage, text: string, params?: TranslationParams): string {
  const translated = TRANSLATIONS[language][text] ?? text;
  return interpolate(translated, params);
}

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Spanish', nativeName: 'Espanol', flag: '🇪🇸' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Portugues', flag: '🇧🇷' },
  { code: 'fr', name: 'French', nativeName: 'Francais', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
];

export const LANGUAGE_STORAGE_KEY = 'celoflow_language';
const LANGUAGE_EVENT = 'celoflow:language-change';

type TranslationMap = Record<string, string>;
export type TranslationParams = Record<string, string | number>;

const TRANSLATIONS: Record<SupportedLanguage, TranslationMap> = {
  en: {
    'Thinking...': 'Thinking...',
    'Routing...': 'Routing...',
    'Checking...': 'Checking...',
    'Finding...': 'Finding...',
    'Loading...': 'Loading...',
    'Error occurred': 'Error occurred',
    'transfer': 'transfer',
    'swap': 'swap',
    'balance': 'balance',
    'contact': 'contact',
    'rates': 'rates',
    'Connect to API': 'Connect to API',
    'Authenticated': 'Authenticated',
    'TEE Verified': 'TEE Verified',
    'Disconnect': 'Disconnect',
    'Clear Data': 'Clear Data',
    'Connected': 'Connected',
    'Unknown': 'Unknown',
    'Balance': 'Balance',
    'Disconnect Wallet': 'Disconnect Wallet',
    'Connect Wallet': 'Connect Wallet',
    'Connect a Wallet': 'Connect a Wallet',
    'Connecting…': 'Connecting…',
    'Copy address': 'Copy address',
    'Contacts': 'Contacts',
    'Method': 'Method',
    'Refresh Token': 'Refresh Token',
  },
  es: {
    Language: 'Idioma',
    Contacts: 'Contactos',
    'How it Works': 'Como funciona',
    Features: 'Funciones',
    Developers: 'Desarrolladores',
    'Launch App': 'Abrir app',
    'SMART AGENT LIVE': 'AGENTE INTELIGENTE ACTIVO',
    'Send Money Like': 'Envia dinero como',
    'You Send a': 'si enviaras un',
    Message: 'mensaje',
    'The financial agent that turns your words into instant global transfers on the Celo blockchain. Simple, secure, and fast.':
      'El agente financiero que convierte tus palabras en transferencias globales instantaneas en la blockchain de Celo. Simple, seguro y rapido.',
    'Try CeloFlow Now': 'Probar CeloFlow',
    'View Activity': 'Ver actividad',
    'Trusted by 10,000+ early users': 'Con la confianza de 10,000+ usuarios tempranos',
    'Just Saved': 'Acabas de ahorrar',
    '$3.50 vs Bank': '$3.50 vs banco',
    'Built for the Real World': 'Disenado para el mundo real',
    'CeloFlow leverages advanced blockchain infrastructure to make money move as freely as information.':
      'CeloFlow aprovecha infraestructura blockchain avanzada para mover dinero tan libremente como la informacion.',
    'Mento Protocol': 'Protocolo Mento',
    'Seamlessly swaps stablecoins (cUSD, cEUR, cREAL) with minimal slippage using decentralized stability mechanisms.':
      'Intercambia stablecoins (cUSD, cEUR, cREAL) con deslizamiento minimo mediante mecanismos de estabilidad descentralizados.',
    'TEE Security': 'Seguridad TEE',
    'Your keys are managed in a Trusted Execution Environment. You authenticate; the enclave signs. No seed phrases to lose.':
      'Tus claves se administran en un Entorno de Ejecucion Confiable. Tu autenticas, el enclave firma. Sin frases semilla.',
    'Gas Abstraction': 'Abstraccion de gas',
    'Pay transaction fees in the same currency you send. No need to hold CELO just to pay for gas.':
      'Paga comisiones en la misma moneda que envias. No necesitas CELO para pagar gas.',
    'Ready to ditch the bank fees?': 'Listo para dejar las comisiones bancarias?',
    'Join the thousands of users saving on every remittance with CeloFlow.':
      'Unete a miles de usuarios que ahorran en cada remesa con CeloFlow.',
    'Enter your email': 'Ingresa tu correo',
    'Get Early Access': 'Obtener acceso temprano',
    'Privacy Policy': 'Politica de privacidad',
    'Terms of Service': 'Terminos del servicio',
    Contact: 'Contacto',
    '© 2024 CeloFlow. Built on Celo.': '© 2024 CeloFlow. Construido en Celo.',
    Connected: 'Conectado',
    Unknown: 'Desconocido',
    Balance: 'Saldo',
    'Disconnect Wallet': 'Desconectar billetera',
    'Connect Wallet': 'Conectar billetera',
    'Connect a Wallet': 'Conectar una billetera',
    'Connecting…': 'Conectando…',
    'Copy address': 'Copiar direccion',
    'Smart Agent v2.1': 'Agente Inteligente v2.1',
    'AI that thinks like a': 'IA que piensa como un',
    'Market Maker.': 'market maker.',
    'CeloFlow scans decentralized exchanges (DEXs) and the Mento Protocol in real-time to find liquidity pools with the lowest slippage, ensuring your family gets the most out of every dollar sent.':
      'CeloFlow analiza DEX y el Protocolo Mento en tiempo real para encontrar pools con menor deslizamiento y maximizar cada dolar enviado.',
    Slippage: 'Deslizamiento',
    'Route Time': 'Tiempo de ruta',
    'Avg. Savings': 'Ahorro prom.',
    'Route Optimization': 'Optimizacion de ruta',
    Active: 'Activo',
    Stablecoin: 'Stablecoin',
    Local: 'Local',
    'TEE Verification Complete': 'Verificacion TEE completada',
    'Key management is handled inside a secure enclave. You never touch a private key.':
      'La gestion de claves se realiza dentro de un enclave seguro. Nunca tocas una clave privada.',
    All: 'Todos',
    Favorites: 'Favoritos',
    Blocked: 'Bloqueado',
    Sort: 'Ordenar',
    Name: 'Nombre',
    Address: 'Direccion',
    Country: 'Pais',
    'Date Added': 'Fecha de alta',
    Export: 'Exportar',
    Import: 'Importar',
    Share: 'Compartir',
    'No matching contacts': 'No hay contactos coincidentes',
    'No contacts yet': 'Aun no hay contactos',
    'Click + to add your first contact': 'Haz clic en + para agregar tu primer contacto',
    'Toggle favorite': 'Alternar favorito',
    'Toggle blocked': 'Alternar bloqueo',
    Edit: 'Editar',
    Delete: 'Eliminar',
    'Delete Contact': 'Eliminar contacto',
    'This action cannot be undone.': 'Esta accion no se puede deshacer.',
    Cancel: 'Cancelar',
    'Edit Contact': 'Editar contacto',
    'New Contact': 'Nuevo contacto',
    'Name is required': 'El nombre es obligatorio',
    'Wallet Address': 'Direccion de wallet',
    'Address is required': 'La direccion es obligatoria',
    Network: 'Red',
    Phone: 'Telefono',
    Email: 'Correo',
    'Invalid email format': 'Formato de correo invalido',
    City: 'Ciudad',
    'Avatar URL': 'URL del avatar',
    Group: 'Grupo',
    Notes: 'Notas',
    Favorite: 'Favorito',
    Update: 'Actualizar',
    Create: 'Crear',
    'John Doe': 'Juan Perez',
    '0x...': '0x...',
    '+1 234 567 8900': '+34 600 000 000',
    'john@example.com': 'juan@ejemplo.com',
    Manila: 'Manila',
    Philippines: 'Filipinas',
    'https://...': 'https://...',
    'Family, Work, etc.': 'Familia, Trabajo, etc.',
    'Additional notes...': 'Notas adicionales...',
    'Contact updated': 'Contacto actualizado',
    'Contact created': 'Contacto creado',
    'Contact deleted': 'Contacto eliminado',
    'Exported {{count}} contacts': 'Se exportaron {{count}} contactos',
    'Import failed': 'Fallo la importacion',
    'Imported {{count}} contacts': 'Se importaron {{count}} contactos',
    ', {{count}} skipped': ', {{count}} omitidos',
    'No contacts to share': 'No hay contactos para compartir',
    'Contacts copied to clipboard': 'Contactos copiados al portapapeles',
    'Share failed': 'Error al compartir',
    'Address copied': 'Direccion copiada',
    '{{count}} contact': '{{count}} contacto',
    '{{count}} contacts': '{{count}} contactos',
    'Add Contact': 'Agregar contacto',
    'Search contacts...': 'Buscar contactos...',
    'All Groups': 'Todos los grupos',
    'CeloFlow Contacts': 'Contactos de CeloFlow',
    "Hi! I'm CeloFlow. I can help you send money globally using the Celo blockchain. Where would you like to send money today?":
      'Hola! Soy CeloFlow. Puedo ayudarte a enviar dinero globalmente con la blockchain de Celo. A donde quieres enviar dinero hoy?',
    'Voice input is not supported in this browser. Please use Chrome, Edge, or Safari.':
      'La entrada por voz no es compatible con este navegador. Usa Chrome, Edge o Safari.',
    'Sorry, I encountered an error connecting to the server. Please try again.':
      'Lo siento, hubo un error al conectar con el servidor. Intentalo de nuevo.',
    'Are you sure you want to cancel this scheduled payment?': 'Seguro que deseas cancelar este pago programado?',
    'CeloFlow Transaction': 'Transaccion de CeloFlow',
    'I just sent {{amount}} {{currency}} to {{recipient}} via CeloFlow!':
      'Acabo de enviar {{amount}} {{currency}} a {{recipient}} con CeloFlow!',
    'Transaction details copied to clipboard!': 'Detalles de la transaccion copiados al portapapeles!',
    'Funds have successfully reached the recipient.': 'Los fondos llegaron correctamente al destinatario.',
    'Transaction is currently being confirmed on the blockchain.':
      'La transaccion se esta confirmando en la blockchain.',
    'Payment is set to execute at a future date.': 'El pago esta programado para ejecutarse luego.',
    'This transaction was cancelled by the user.': 'Esta transaccion fue cancelada por el usuario.',
    'Transaction could not be completed. Please try again.':
      'No se pudo completar la transaccion. Intentalo nuevamente.',
    Online: 'En linea',
    'Transaction History': 'Historial de transacciones',
    'Recent Activity': 'Actividad reciente',
    'Search recipient or currency...': 'Buscar destinatario o moneda...',
    'No transactions yet.': 'Aun no hay transacciones.',
    'No matching transactions.': 'No hay transacciones coincidentes.',
    'Cancel Scheduled Payment': 'Cancelar pago programado',
    Sent: 'Enviado',
    Received: 'Recibido',
    '{{frequency}} starting {{startDate}}': '{{frequency}} desde {{startDate}}',
    'Best Quote Found': 'Mejor cotizacion encontrada',
    'Saved ${{amount}}': 'Ahorraste ${{amount}}',
    'You Send': 'Tu envias',
    Receives: 'Recibe',
    'Live Real-time Rate': 'Tasa en tiempo real',
    'Estimated Fallback Rate': 'Tasa estimada de respaldo',
    'Payment Schedule': 'Programacion de pago',
    'One-time': 'Una vez',
    Daily: 'Diario',
    Weekly: 'Semanal',
    Monthly: 'Mensual',
    'Mento Protocol Status': 'Estado del Protocolo Mento',
    Optimal: 'Optimo',
    'Total Network Fees': 'Comisiones totales de red',
    'Mento Swap Fee': 'Comision de swap Mento',
    'Celo Gas Fee': 'Comision de gas Celo',
    'Secure Enclave (TEE)': 'Enclave seguro (TEE)',
    'Est. Arrival': 'Llegada estimada',
    '< 5 seconds': '< 5 segundos',
    Scheduled: 'Programado',
    'Schedule Payment': 'Programar pago',
    'Confirm Transfer': 'Confirmar transferencia',
    'Payment Scheduled!': 'Pago programado!',
    'Transaction Sent!': 'Transaccion enviada!',
    '{{amount}} {{currency}} will be sent to {{recipient}} {{frequency}} starting {{startDate}}.':
      '{{amount}} {{currency}} se enviaran a {{recipient}} {{frequency}} a partir de {{startDate}}.',
    '{{amount}} {{currency}} is on its way to {{recipient}}.':
      '{{amount}} {{currency}} van en camino a {{recipient}}.',
    'View on CeloScan': 'Ver en CeloScan',
    'Processing request...': 'Procesando solicitud...',
    'Speak to CeloFlow': 'Hablar con CeloFlow',
    'Listening...': 'Escuchando...',
    'Type a command...': 'Escribe un comando...',
    completed: 'completada',
    processing: 'procesando',
    scheduled: 'programada',
    cancelled: 'cancelada',
    failed: 'fallida',
    'Send 50 cUSD to Mom in Philippines': 'Enviar 50 cUSD a mama en Filipinas',
    'Transfer 200 EUR to Juan in Mexico': 'Transferir 200 EUR a Juan en Mexico',
    'Pay landlord 15000 KES via M-Pesa': 'Pagar alquiler 15000 KES por M-Pesa',
    'Send 100 cUSD to Dad every month': 'Enviar 100 cUSD a papa cada mes',
    'Thinking...': 'Pensando...',
    'Routing...': 'Enrutando...',
    'Checking...': 'Verificando...',
    'Finding...': 'Buscando...',
    'Loading...': 'Cargando...',
    'Error occurred': 'Ocurrió un error',
    'transfer': 'transferencia',
    'swap': 'intercambio',
    'balance': 'saldo',
    'contact': 'contacto',
    'rates': 'tasas',
  },
  pt: {
    Language: 'Idioma',
    Contacts: 'Contatos',
    'How it Works': 'Como funciona',
    Features: 'Recursos',
    Developers: 'Desenvolvedores',
    'Launch App': 'Abrir app',
    'SMART AGENT LIVE': 'AGENTE INTELIGENTE AO VIVO',
    'Send Money Like': 'Envie dinheiro como',
    'You Send a': 'se estivesse enviando uma',
    Message: 'mensagem',
    'The financial agent that turns your words into instant global transfers on the Celo blockchain. Simple, secure, and fast.':
      'O agente financeiro que transforma suas palavras em transferencias globais instantaneas na blockchain Celo. Simples, seguro e rapido.',
    'Try CeloFlow Now': 'Experimentar CeloFlow',
    'View Activity': 'Ver atividade',
    'Trusted by 10,000+ early users': 'Confiado por 10.000+ usuarios iniciais',
    'Just Saved': 'Acabou de economizar',
    '$3.50 vs Bank': '$3.50 vs banco',
    'Built for the Real World': 'Feito para o mundo real',
    'CeloFlow leverages advanced blockchain infrastructure to make money move as freely as information.':
      'CeloFlow usa infraestrutura blockchain avancada para mover dinheiro com a mesma liberdade da informacao.',
    'Mento Protocol': 'Protocolo Mento',
    'Seamlessly swaps stablecoins (cUSD, cEUR, cREAL) with minimal slippage using decentralized stability mechanisms.':
      'Troca stablecoins (cUSD, cEUR, cREAL) com baixo slippage usando mecanismos descentralizados de estabilidade.',
    'TEE Security': 'Seguranca TEE',
    'Your keys are managed in a Trusted Execution Environment. You authenticate; the enclave signs. No seed phrases to lose.':
      'Suas chaves sao gerenciadas em um Trusted Execution Environment. Voce autentica; o enclave assina.',
    'Gas Abstraction': 'Abstracao de gas',
    'Pay transaction fees in the same currency you send. No need to hold CELO just to pay for gas.':
      'Pague taxas na mesma moeda que envia. Nao precisa manter CELO apenas para gas.',
    'Ready to ditch the bank fees?': 'Pronto para largar as taxas bancarias?',
    'Join the thousands of users saving on every remittance with CeloFlow.':
      'Junte-se a milhares de usuarios economizando em cada remessa com CeloFlow.',
    'Enter your email': 'Digite seu email',
    'Get Early Access': 'Obter acesso antecipado',
    'Privacy Policy': 'Politica de privacidade',
    'Terms of Service': 'Termos de servico',
    Contact: 'Contato',
    '© 2024 CeloFlow. Built on Celo.': '© 2024 CeloFlow. Construido na Celo.',
    Connected: 'Conectado',
    Unknown: 'Desconhecido',
    Balance: 'Saldo',
    'Disconnect Wallet': 'Desconectar carteira',
    'Connect Wallet': 'Conectar carteira',
    'Connect a Wallet': 'Conectar carteira',
    'Connecting…': 'Conectando…',
    'Copy address': 'Copiar endereco',
    'Smart Agent v2.1': 'Agente Inteligente v2.1',
    'AI that thinks like a': 'IA que pensa como um',
    'Market Maker.': 'market maker.',
    'CeloFlow scans decentralized exchanges (DEXs) and the Mento Protocol in real-time to find liquidity pools with the lowest slippage, ensuring your family gets the most out of every dollar sent.':
      'CeloFlow analisa DEX e o Protocolo Mento em tempo real para achar pools com menor slippage e maximizar cada dolar enviado.',
    Slippage: 'Slippage',
    'Route Time': 'Tempo de rota',
    'Avg. Savings': 'Economia media',
    'Route Optimization': 'Otimizacao de rota',
    Active: 'Ativo',
    Stablecoin: 'Stablecoin',
    Local: 'Local',
    'TEE Verification Complete': 'Verificacao TEE concluida',
    'Key management is handled inside a secure enclave. You never touch a private key.':
      'O gerenciamento de chaves ocorre em um enclave seguro. Voce nunca toca em uma chave privada.',
    All: 'Todos',
    Favorites: 'Favoritos',
    Blocked: 'Bloqueado',
    Sort: 'Ordenar',
    Name: 'Nome',
    Address: 'Endereco',
    Country: 'Pais',
    'Date Added': 'Data de cadastro',
    Export: 'Exportar',
    Import: 'Importar',
    Share: 'Compartilhar',
    'No matching contacts': 'Nenhum contato correspondente',
    'No contacts yet': 'Nenhum contato ainda',
    'Click + to add your first contact': 'Clique em + para adicionar seu primeiro contato',
    'Toggle favorite': 'Alternar favorito',
    'Toggle blocked': 'Alternar bloqueio',
    Edit: 'Editar',
    Delete: 'Excluir',
    'Delete Contact': 'Excluir contato',
    'This action cannot be undone.': 'Esta acao nao pode ser desfeita.',
    Cancel: 'Cancelar',
    'Edit Contact': 'Editar contato',
    'New Contact': 'Novo contato',
    'Name is required': 'Nome e obrigatorio',
    'Wallet Address': 'Endereco da carteira',
    'Address is required': 'Endereco e obrigatorio',
    Network: 'Rede',
    Phone: 'Telefone',
    Email: 'Email',
    'Invalid email format': 'Formato de email invalido',
    City: 'Cidade',
    'Avatar URL': 'URL do avatar',
    Group: 'Grupo',
    Notes: 'Notas',
    Favorite: 'Favorito',
    Update: 'Atualizar',
    Create: 'Criar',
    'John Doe': 'Joao Silva',
    '0x...': '0x...',
    '+1 234 567 8900': '+55 11 99999-9999',
    'john@example.com': 'joao@exemplo.com',
    Manila: 'Manila',
    Philippines: 'Filipinas',
    'https://...': 'https://...',
    'Family, Work, etc.': 'Familia, Trabalho, etc.',
    'Additional notes...': 'Notas adicionais...',
    'Contact updated': 'Contato atualizado',
    'Contact created': 'Contato criado',
    'Contact deleted': 'Contato removido',
    'Exported {{count}} contacts': '{{count}} contatos exportados',
    'Import failed': 'Falha na importacao',
    'Imported {{count}} contacts': '{{count}} contatos importados',
    ', {{count}} skipped': ', {{count}} ignorados',
    'No contacts to share': 'Nao ha contatos para compartilhar',
    'Contacts copied to clipboard': 'Contatos copiados para a area de transferencia',
    'Share failed': 'Falha ao compartilhar',
    'Address copied': 'Endereco copiado',
    '{{count}} contact': '{{count}} contato',
    '{{count}} contacts': '{{count}} contatos',
    'Add Contact': 'Adicionar contato',
    'Search contacts...': 'Buscar contatos...',
    'All Groups': 'Todos os grupos',
    'CeloFlow Contacts': 'Contatos CeloFlow',
    "Hi! I'm CeloFlow. I can help you send money globally using the Celo blockchain. Where would you like to send money today?":
      'Oi! Eu sou o CeloFlow. Posso ajudar voce a enviar dinheiro globalmente usando a blockchain Celo. Para onde voce quer enviar dinheiro hoje?',
    'Voice input is not supported in this browser. Please use Chrome, Edge, or Safari.':
      'Entrada por voz nao e suportada neste navegador. Use Chrome, Edge ou Safari.',
    'Sorry, I encountered an error connecting to the server. Please try again.':
      'Desculpe, ocorreu um erro ao conectar ao servidor. Tente novamente.',
    'Are you sure you want to cancel this scheduled payment?':
      'Tem certeza que deseja cancelar este pagamento agendado?',
    'CeloFlow Transaction': 'Transacao CeloFlow',
    'I just sent {{amount}} {{currency}} to {{recipient}} via CeloFlow!':
      'Acabei de enviar {{amount}} {{currency}} para {{recipient}} via CeloFlow!',
    'Transaction details copied to clipboard!':
      'Detalhes da transacao copiados para a area de transferencia!',
    'Funds have successfully reached the recipient.':
      'Os fundos chegaram ao destinatario com sucesso.',
    'Transaction is currently being confirmed on the blockchain.':
      'A transacao esta sendo confirmada na blockchain.',
    'Payment is set to execute at a future date.':
      'O pagamento esta agendado para execucao futura.',
    'This transaction was cancelled by the user.':
      'Esta transacao foi cancelada pelo usuario.',
    'Transaction could not be completed. Please try again.':
      'A transacao nao pode ser concluida. Tente novamente.',
    Online: 'Online',
    'Transaction History': 'Historico de transacoes',
    'Recent Activity': 'Atividade recente',
    'Search recipient or currency...': 'Buscar destinatario ou moeda...',
    'No transactions yet.': 'Nenhuma transacao ainda.',
    'No matching transactions.': 'Nenhuma transacao correspondente.',
    'Cancel Scheduled Payment': 'Cancelar pagamento agendado',
    Sent: 'Enviado',
    Received: 'Recebido',
    '{{frequency}} starting {{startDate}}': '{{frequency}} a partir de {{startDate}}',
    'Best Quote Found': 'Melhor cotacao encontrada',
    'Saved ${{amount}}': 'Economizou ${{amount}}',
    'You Send': 'Voce envia',
    Receives: 'Recebe',
    'Live Real-time Rate': 'Cotacao em tempo real',
    'Estimated Fallback Rate': 'Cotacao estimada de backup',
    'Payment Schedule': 'Agendamento de pagamento',
    'One-time': 'Unico',
    Daily: 'Diario',
    Weekly: 'Semanal',
    Monthly: 'Mensal',
    'Mento Protocol Status': 'Status do Protocolo Mento',
    Optimal: 'Otimo',
    'Total Network Fees': 'Taxas totais de rede',
    'Mento Swap Fee': 'Taxa de swap Mento',
    'Celo Gas Fee': 'Taxa de gas Celo',
    'Secure Enclave (TEE)': 'Enclave seguro (TEE)',
    'Est. Arrival': 'Chegada estimada',
    '< 5 seconds': '< 5 segundos',
    Scheduled: 'Agendado',
    'Schedule Payment': 'Agendar pagamento',
    'Confirm Transfer': 'Confirmar transferencia',
    'Payment Scheduled!': 'Pagamento agendado!',
    'Transaction Sent!': 'Transacao enviada!',
    '{{amount}} {{currency}} will be sent to {{recipient}} {{frequency}} starting {{startDate}}.':
      '{{amount}} {{currency}} sera enviado para {{recipient}} {{frequency}} a partir de {{startDate}}.',
    '{{amount}} {{currency}} is on its way to {{recipient}}.':
      '{{amount}} {{currency}} esta a caminho de {{recipient}}.',
    'View on CeloScan': 'Ver no CeloScan',
    'Processing request...': 'Processando solicitacao...',
    'Speak to CeloFlow': 'Falar com CeloFlow',
    'Listening...': 'Ouvindo...',
    'Type a command...': 'Digite um comando...',
    completed: 'concluida',
    processing: 'processando',
    scheduled: 'agendada',
    cancelled: 'cancelada',
    failed: 'falhou',
    'Send 50 cUSD to Mom in Philippines': 'Enviar 50 cUSD para mae nas Filipinas',
    'Transfer 200 EUR to Juan in Mexico': 'Transferir 200 EUR para Juan no Mexico',
    'Pay landlord 15000 KES via M-Pesa': 'Pagar aluguel de 15000 KES via M-Pesa',
    'Send 100 cUSD to Dad every month': 'Enviar 100 cUSD para pai todo mes',
    'Thinking...': 'Pensando...',
    'Routing...': 'Encontrando rota...',
    'Checking...': 'Verificando...',
    'Finding...': 'Buscando...',
    'Loading...': 'Carregando...',
    'Error occurred': 'Ocorreu um erro',
    'transfer': 'transferencia',
    'swap': 'troca',
    'balance': 'saldo',
    'contact': 'contato',
    'rates': 'taxas',
  },
  fr: {
    Language: 'Langue',
    Contacts: 'Contacts',
    'How it Works': 'Comment ça marche',
    Features: 'Fonctionnalités',
    Developers: 'Développeurs',
    'Launch App': 'Lancer l\'app',
    'SMART AGENT LIVE': 'AGENT INTELLIGENT EN DIRECT',
    'Send Money Like': 'Envoyez de l\'argent comme',
    'You Send a': 'Vous envoyez un',
    Message: 'Message',
    'The financial agent that turns your words into instant global transfers on the Celo blockchain. Simple, secure, and fast.':
      'L\'agent financier qui transforme vos mots en transferts mondiaux instantanés sur la blockchain Celo. Simple, sécurisé et rapide.',
    'Try CeloFlow Now': 'Essayez CeloFlow maintenant',
    'View Activity': 'Voir l\'activité',
    'Trusted by 10,000+ early users': 'Approuvé par plus de 10 000 utilisateurs',
    'Just Saved': 'Économie',
    '$3.50 vs Bank': '$3.50 vs Banque',
    'Built for the Real World': 'Conçu pour le monde réel',
    'CeloFlow leverages advanced blockchain infrastructure to make money move as freely as information.':
      'CeloFlow exploite une infrastructure blockchain avancée pour faire circuler l\'argent aussi librement que l\'information.',
    'Mento Protocol': 'Protocole Mento',
    'Seamlessly swaps stablecoins (cUSD, cEUR, cREAL) with minimal slippage using decentralized stability mechanisms.':
      'Échange sans friction de stablecoins (cUSD, cEUR, cREAL) avec un slippage minimal via des mécanismes de stabilité décentralisés.',
    'TEE Security': 'Sécurité TEE',
    'Your keys are managed in a Trusted Execution Environment. You authenticate; the enclave signs. No seed phrases to lose.':
      'Vos clés sont gérées dans un environnement d\'exécution sécurisé. Vous vous authentifiez ; l\'enclave signe. Aucune phrase de graine à perdre.',
    'Gas Abstraction': 'Abstraction du gaz',
    'Pay transaction fees in the same currency you send. No need to hold CELO just to pay for gas.':
      'Payez les frais de transaction dans la même devise que vous envoyez. Pas besoin de détenir du CELO pour payer le gaz.',
    'Ready to ditch the bank fees?': 'Prêt à vous débarrasser des frais bancaires ?',
    'Join the thousands of users saving on every remittance with CeloFlow.':
      'Rejoignez les milliers d\'utilisateurs qui économisent sur chaque transfert avec CeloFlow.',
    'Enter your email': 'Entrez votre email',
    'Get Early Access': 'Accès anticipé',
    'Privacy Policy': 'Politique de confidentialité',
    'Terms of Service': 'Conditions d\'utilisation',
    Contact: 'Contact',
    '© 2024 CeloFlow. Built on Celo.': '© 2024 CeloFlow. Construit sur Celo.',
    Connected: 'Connecté',
    Unknown: 'Inconnu',
    Balance: 'Solde',
    'Disconnect Wallet': 'Déconnecter le portefeuille',
    'Connect Wallet': 'Connecter le portefeuille',
    'Connect a Wallet': 'Connecter un portefeuille',
    'Connecting…': 'Connexion...',
    'Copy address': 'Copier l\'adresse',
    'Smart Agent v2.1': 'Agent intelligent v2.1',
    'AI that thinks like a': 'IA qui pense comme un',
    'Market Maker.': 'Market maker.',
    'CeloFlow scans decentralized exchanges (DEXs) and the Mento Protocol in real-time to find liquidity pools with the lowest slippage, ensuring your family gets the most out of every dollar sent.':
      'CeloFlow analyse les échanges décentralisés (DEX) et le protocole Mento en temps réel pour trouver des pools de liquidité avec le slippage le plus faible, garantissant à votre famille d\'obtenir le meilleur de chaque dollar envoyé.',
    Slippage: 'Slippage',
    'Route Time': 'Temps de route',
    'Avg. Savings': 'Économie moyenne',
    'Route Optimization': 'Optimisation de route',
    Active: 'Actif',
    Stablecoin: 'Stablecoin',
    Local: 'Local',
    'TEE Verification Complete': 'Vérification TEE terminée',
    'Key management is handled inside a secure enclave. You never touch a private key.':
      'La gestion des clés se fait dans une enclave sécurisée. Vous ne touchez jamais de clé privée.',
    All: 'Tous',
    Favorites: 'Favoris',
    Blocked: 'Bloqués',
    Sort: 'Trier',
    Name: 'Nom',
    Address: 'Adresse',
    Country: 'Pays',
    'Date Added': 'Date d\'ajout',
    Export: 'Exporter',
    Import: 'Importer',
    Share: 'Partager',
    'No matching contacts': 'Aucun contact correspondant',
    'No contacts yet': 'Aucun contact pour le moment',
    'Click + to add your first contact': 'Cliquez sur + pour ajouter votre premier contact',
    'Toggle favorite': 'Basculer favori',
    'Toggle blocked': 'Basculer bloqué',
    Edit: 'Modifier',
    Delete: 'Supprimer',
    'Delete Contact': 'Supprimer le contact',
    'This action cannot be undone.': 'Cette action ne peut pas être annulée.',
    Cancel: 'Annuler',
    'Edit Contact': 'Modifier le contact',
    'New Contact': 'Nouveau contact',
    'Name is required': 'Le nom est requis',
    'Wallet Address': 'Adresse du portefeuille',
    'Address is required': 'L\'adresse est requise',
    Network: 'Réseau',
    Phone: 'Téléphone',
    Email: 'Email',
    'Invalid email format': 'Format d\'email invalide',
    City: 'Ville',
    'Avatar URL': 'URL de l\'avatar',
    Group: 'Groupe',
    Notes: 'Notes',
    Favorite: 'Favori',
    Update: 'Mettre à jour',
    Create: 'Créer',
    'John Doe': 'Jean Dupont',
    '0x...': '0x...',
    '+1 234 567 8900': '+33 1 23 45 67 89',
    'john@example.com': 'jean@exemple.com',
    Manila: 'Manille',
    Philippines: 'Philippines',
    'https://...': 'https://...',
    'Family, Work, etc.': 'Famille, Travail, etc.',
    'Additional notes...': 'Notes supplémentaires...',
    'Contact updated': 'Contact mis à jour',
    'Contact created': 'Contact créé',
    'Contact deleted': 'Contact supprimé',
    'Exported {{count}} contacts': '{{count}} contacts exportés',
    'Import failed': 'Échec de l\'importation',
    'Imported {{count}} contacts': '{{count}} contacts importés',
    ', {{count}} skipped': ', {{count}} ignorés',
    'No contacts to share': 'Aucun contact à partager',
    'Contacts copied to clipboard': 'Contacts copiés dans le presse-papiers',
    'Share failed': 'Échec du partage',
    'Address copied': 'Adresse copiée',
    '{{count}} contact': '{{count}} contact',
    '{{count}} contacts': '{{count}} contacts',
    'Add Contact': 'Ajouter un contact',
    'Search contacts...': 'Rechercher des contacts...',
    'All Groups': 'Tous les groupes',
    'CeloFlow Contacts': 'Contacts CeloFlow',
    "Hi! I'm CeloFlow. I can help you send money globally using the Celo blockchain. Where would you like to send money today?":
      'Bonjour ! Je suis CeloFlow. Je peux vous aider à envoyer de l\'argent dans le monde entier via la blockchain Celo. Où aimeriez-vous envoyer de l\'argent aujourd\'hui ?',
    'Voice input is not supported in this browser. Please use Chrome, Edge, or Safari.':
      'L\'entrée vocale n\'est pas prise en charge dans ce navigateur. Veuillez utiliser Chrome, Edge ou Safari.',
    'Sorry, I encountered an error connecting to the server. Please try again.':
      'Désolé, une erreur s\'est produite lors de la connexion au serveur. Veuillez réessayer.',
    'Are you sure you want to cancel this scheduled payment?':
      'Êtes-vous sûr de vouloir annuler ce paiement programmé ?',
    'CeloFlow Transaction': 'Transaction CeloFlow',
    'I just sent {{amount}} {{currency}} to {{recipient}} via CeloFlow!':
      'Je viens d\'envoyer {{amount}} {{currency}} à {{recipient}} via CeloFlow !',
    'Transaction details copied to clipboard!': 'Détails de la transaction copiés dans le presse-papiers !',
    'Funds have successfully reached the recipient.': 'Les fonds ont atteint le destinataire avec succès.',
    'Transaction is currently being confirmed on the blockchain.':
      'La transaction est en cours de confirmation sur la blockchain.',
    'Payment is set to execute at a future date.': 'Le paiement est programmé pour être exécuté à une date future.',
    'This transaction was cancelled by the user.': 'Cette transaction a été annulée par l\'utilisateur.',
    'Transaction could not be completed. Please try again.':
      'La transaction n\'a pas pu être complétée. Veuillez réessayer.',
    Online: 'En ligne',
    'Transaction History': 'Historique des transactions',
    'Recent Activity': 'Activité récente',
    'Search recipient or currency...': 'Rechercher le destinataire ou la devise...',
    'No transactions yet.': 'Aucune transaction pour le moment.',
    'No matching transactions.': 'Aucune transaction correspondante.',
    'Cancel Scheduled Payment': 'Annuler le paiement programmé',
    Sent: 'Envoyé',
    Received: 'Reçu',
    '{{frequency}} starting {{startDate}}': '{{frequency}} à partir du {{startDate}}',
    'Best Quote Found': 'Meilleur devis trouvé',
    'Saved ${{amount}}': 'Économisé ${{amount}}',
    'You Send': 'Vous envoyez',
    Receives: 'Reçoit',
    'Live Real-time Rate': 'Taux en temps réel',
    'Estimated Fallback Rate': 'Taux de repli estimé',
    'Payment Schedule': 'Programme de paiement',
    'One-time': 'Unique',
    Daily: 'Quotidien',
    Weekly: 'Hebdomadaire',
    Monthly: 'Mensuel',
    'Mento Protocol Status': 'Statut du protocole Mento',
    Optimal: 'Optimal',
    'Total Network Fees': 'Frais réseau totaux',
    'Mento Swap Fee': 'Frais d\'échange Mento',
    'Celo Gas Fee': 'Frais de gaz Celo',
    'Secure Enclave (TEE)': 'Enclave sécurisée (TEE)',
    'Est. Arrival': 'Arrivée estimée',
    '< 5 seconds': '< 5 secondes',
    Scheduled: 'Programmé',
    'Schedule Payment': 'Programmer un paiement',
    'Confirm Transfer': 'Confirmer le transfert',
    'Payment Scheduled!': 'Paiement programmé !',
    'Transaction Sent!': 'Transaction envoyée !',
    '{{amount}} {{currency}} will be sent to {{recipient}} {{frequency}} starting {{startDate}}.':
      '{{amount}} {{currency}} seront envoyés à {{recipient}} {{frequency}} à partir du {{startDate}}.',
    '{{amount}} {{currency}} is on its way to {{recipient}}.':
      '{{amount}} {{currency}} sont en route vers {{recipient}}.',
    'View on CeloScan': 'Voir sur CeloScan',
    'Processing request...': 'Traitement de la demande...',
    'Speak to CeloFlow': 'Parler à CeloFlow',
    'Listening...': 'Écoute...',
    'Type a command...': 'Tapez une commande...',
    completed: 'terminée',
    processing: 'en cours',
    scheduled: 'programmée',
    cancelled: 'annulée',
    failed: 'échouée',
    'Send 50 cUSD to Mom in Philippines': 'Envoyer 50 cUSD à maman aux Philippines',
    'Transfer 200 EUR to Juan in Mexico': 'Transférer 200 EUR à Juan au Mexique',
    'Pay landlord 15000 KES via M-Pesa': 'Payer le loyer 15000 KES via M-Pesa',
    'Send 100 cUSD to Dad every month': 'Envoyer 100 cUSD à papa chaque mois',
    'Thinking...': 'Réflexion...',
    'Routing...': 'Routage...',
    'Checking...': 'Vérification...',
    'Finding...': 'Recherche...',
    'Loading...': 'Chargement...',
    'Error occurred': 'Une erreur est survenue',
    'transfer': 'transfert',
    'swap': 'échange',
    'balance': 'solde',
    'contact': 'contact',
    'rates': 'taux',
  },
  de: {
    Language: 'Sprache',
    Contacts: 'Kontakte',
    'How it Works': 'Wie es funktioniert',
    Features: 'Funktionen',
    Developers: 'Entwickler',
    'Launch App': 'App starten',
    'SMART AGENT LIVE': 'SMART AGENT LIVE',
    'Send Money Like': 'Senden Sie Geld wie',
    'You Send a': 'Sie senden eine',
    Message: 'Nachricht',
    'The financial agent that turns your words into instant global transfers on the Celo blockchain. Simple, secure, and fast.':
      'Der Finanzagent, der Ihre Worte in sofortige globale Überweisungen auf der Celo-Blockchain umwandelt. Einfach, sicher und schnell.',
    'Try CeloFlow Now': 'CeloFlow jetzt testen',
    'View Activity': 'Aktivität anzeigen',
    'Trusted by 10,000+ early users': 'Vertraut von über 10.000 Frühnutzern',
    'Just Saved': 'Gespart',
    '$3.50 vs Bank': '$3.50 vs Bank',
    'Built for the Real World': 'Für die reale Welt gebaut',
    'CeloFlow leverages advanced blockchain infrastructure to make money move as freely as information.':
      'CeloFlow nutzt fortschrittliche Blockchain-Infrastruktur, um Geld so frei fließen zu lassen wie Informationen.',
    'Mento Protocol': 'Mento-Protokoll',
    'Seamlessly swaps stablecoins (cUSD, cEUR, cREAL) with minimal slippage using decentralized stability mechanisms.':
      'Nahtloser Tausch von Stablecoins (cUSD, cEUR, cREAL) mit minimalem Slippage durch dezentrale Stabilitätsmechanismen.',
    'TEE Security': 'TEE-Sicherheit',
    'Your keys are managed in a Trusted Execution Environment. You authenticate; the enclave signs. No seed phrases to lose.':
      'Ihre Schlüssel werden in einer vertrauenswürdigen Ausführungsumgebung verwaltet. Sie authentifizieren sich; die Enclave signiert. Keine Seed-Phrasen zu verlieren.',
    'Gas Abstraction': 'Gas-Abstraktion',
    'Pay transaction fees in the same currency you send. No need to hold CELO just to pay for gas.':
      'Zahlen Sie Transaktionsgebühren in derselben Währung, die Sie senden. CELO nur für Gas-Gebühren halten ist nicht nötig.',
    'Ready to ditch the bank fees?': 'Bereit, die Bankgebühren loszuwerden?',
    'Join the thousands of users saving on every remittance with CeloFlow.':
      'Schließen Sie sich Tausenden von Benutzern an, die mit CeloFlow bei jeder Überweisung sparen.',
    'Enter your email': 'E-Mail eingeben',
    'Get Early Access': 'Frühzugang erhalten',
    'Privacy Policy': 'Datenschutzerklärung',
    'Terms of Service': 'Nutzungsbedingungen',
    Contact: 'Kontakt',
    '© 2024 CeloFlow. Built on Celo.': '© 2024 CeloFlow. Gebaut auf Celo.',
    Connected: 'Verbunden',
    Unknown: 'Unbekannt',
    Balance: 'Guthaben',
    'Disconnect Wallet': 'Wallet trennen',
    'Connect Wallet': 'Wallet verbinden',
    'Connect a Wallet': 'Wallet verbinden',
    'Connecting…': 'Verbinden...',
    'Copy address': 'Adresse kopieren',
    'Smart Agent v2.1': 'Smart Agent v2.1',
    'AI that thinks like a': 'KI, die denkt wie ein',
    'Market Maker.': 'Market Maker.',
    'CeloFlow scans decentralized exchanges (DEXs) and the Mento Protocol in real-time to find liquidity pools with the lowest slippage, ensuring your family gets the most out of every dollar sent.':
      'CeloFlow scannt dezentrale Börsen (DEXs) und das Mento-Protokoll in Echtzeit, um Liquiditätspools mit dem geringsten Slippage zu finden und sicherzustellen, dass Ihre Familie das meiste aus jedem gesendeten Dollar herausholt.',
    Slippage: 'Slippage',
    'Route Time': 'Routenzeit',
    'Avg. Savings': 'Durchschn. Ersparnis',
    'Route Optimization': 'Routenoptimierung',
    Active: 'Aktiv',
    Stablecoin: 'Stablecoin',
    Local: 'Lokal',
    'TEE Verification Complete': 'TEE-Verifizierung abgeschlossen',
    'Key management is handled inside a secure enclave. You never touch a private key.':
      'Schlüsselverwaltung erfolgt in einer sicheren Enclave. Sie berühren niemals einen privaten Schlüssel.',
    All: 'Alle',
    Favorites: 'Favoriten',
    Blocked: 'Blockiert',
    Sort: 'Sortieren',
    Name: 'Name',
    Address: 'Adresse',
    Country: 'Land',
    'Date Added': 'Hinzugefügt am',
    Export: 'Exportieren',
    Import: 'Importieren',
    Share: 'Teilen',
    'No matching contacts': 'Keine passenden Kontakte',
    'No contacts yet': 'Noch keine Kontakte',
    'Click + to add your first contact': 'Klicken Sie auf +, um Ihren ersten Kontakt hinzuzufügen',
    'Toggle favorite': 'Favorit umschalten',
    'Toggle blocked': 'Blockiert umschalten',
    Edit: 'Bearbeiten',
    Delete: 'Löschen',
    'Delete Contact': 'Kontakt löschen',
    'This action cannot be undone.': 'Diese Aktion kann nicht rückgängig gemacht werden.',
    Cancel: 'Abbrechen',
    'Edit Contact': 'Kontakt bearbeiten',
    'New Contact': 'Neuer Kontakt',
    'Name is required': 'Name ist erforderlich',
    'Wallet Address': 'Wallet-Adresse',
    'Address is required': 'Adresse ist erforderlich',
    Network: 'Netzwerk',
    Phone: 'Telefon',
    Email: 'E-Mail',
    'Invalid email format': 'Ungültiges E-Mail-Format',
    City: 'Stadt',
    'Avatar URL': 'Avatar-URL',
    Group: 'Gruppe',
    Notes: 'Notizen',
    Favorite: 'Favorit',
    Update: 'Aktualisieren',
    Create: 'Erstellen',
    'John Doe': 'Max Mustermann',
    '0x...': '0x...',
    '+1 234 567 8900': '+49 30 12345678',
    'john@example.com': 'max@beispiel.de',
    Manila: 'Manila',
    Philippines: 'Philippinen',
    'https://...': 'https://...',
    'Family, Work, etc.': 'Familie, Arbeit, etc.',
    'Additional notes...': 'Zusätzliche Notizen...',
    'Contact updated': 'Kontakt aktualisiert',
    'Contact created': 'Kontakt erstellt',
    'Contact deleted': 'Kontakt gelöscht',
    'Exported {{count}} contacts': '{{count}} Kontakte exportiert',
    'Import failed': 'Import fehlgeschlagen',
    'Imported {{count}} contacts': '{{count}} Kontakte importiert',
    ', {{count}} skipped': ', {{count}} übersprungen',
    'No contacts to share': 'Keine Kontakte zum Teilen',
    'Contacts copied to clipboard': 'Kontakte in Zwischenablage kopiert',
    'Share failed': 'Teilen fehlgeschlagen',
    'Address copied': 'Adresse kopiert',
    '{{count}} contact': '{{count}} Kontakt',
    '{{count}} contacts': '{{count}} Kontakte',
    'Add Contact': 'Kontakt hinzufügen',
    'Search contacts...': 'Kontakte suchen...',
    'All Groups': 'Alle Gruppen',
    'CeloFlow Contacts': 'CeloFlow-Kontakte',
    "Hi! I'm CeloFlow. I can help you send money globally using the Celo blockchain. Where would you like to send money today?":
      'Hallo! Ich bin CeloFlow. Ich kann Ihnen helfen, Geld weltweit über die Celo-Blockchain zu senden. Wohin möchten Sie heute Geld senden?',
    'Voice input is not supported in this browser. Please use Chrome, Edge, or Safari.':
      'Spracheingabe wird in diesem Browser nicht unterstützt. Bitte verwenden Sie Chrome, Edge oder Safari.',
    'Sorry, I encountered an error connecting to the server. Please try again.':
      'Entschuldigung, es gab einen Fehler beim Verbinden mit dem Server. Bitte versuchen Sie es erneut.',
    'Are you sure you want to cancel this scheduled payment?':
      'Sind Sie sicher, dass Sie diese geplante Zahlung stornieren möchten?',
    'CeloFlow Transaction': 'CeloFlow-Transaktion',
    'I just sent {{amount}} {{currency}} to {{recipient}} via CeloFlow!':
      'Ich habe gerade {{amount}} {{currency}} an {{recipient}} über CeloFlow gesendet!',
    'Transaction details copied to clipboard!': 'Transaktionsdetails in Zwischenablage kopiert!',
    'Funds have successfully reached the recipient.': 'Fonds haben den Empfänger erfolgreich erreicht.',
    'Transaction is currently being confirmed on the blockchain.':
      'Transaktion wird derzeit auf der Blockchain bestätigt.',
    'Payment is set to execute at a future date.': 'Zahlung ist für zukünftige Ausführung geplant.',
    'This transaction was cancelled by the user.': 'Diese Transaktion wurde vom Benutzer storniert.',
    'Transaction could not be completed. Please try again.':
      'Transaktion konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.',
    Online: 'Online',
    'Transaction History': 'Transaktionsverlauf',
    'Recent Activity': 'Letzte Aktivität',
    'Search recipient or currency...': 'Empfänger oder Währung suchen...',
    'No transactions yet.': 'Noch keine Transaktionen.',
    'No matching transactions.': 'Keine passenden Transaktionen.',
    'Cancel Scheduled Payment': 'Geplante Zahlung stornieren',
    Sent: 'Gesendet',
    Received: 'Empfangen',
    '{{frequency}} starting {{startDate}}': '{{frequency}} ab dem {{startDate}}',
    'Best Quote Found': 'Bester Preis gefunden',
    'Saved ${{amount}}': '${{amount}} gespart',
    'You Send': 'Sie senden',
    Receives: 'Empfängt',
    'Live Real-time Rate': 'Echtzeitkurs',
    'Estimated Fallback Rate': 'Geschätzter Fallback-Kurs',
    'Payment Schedule': 'Zahlungsplan',
    'One-time': 'Einmalig',
    Daily: 'Täglich',
    Weekly: 'Wöchentlich',
    Monthly: 'Monatlich',
    'Mento Protocol Status': 'Mento-Protokoll-Status',
    Optimal: 'Optimal',
    'Total Network Fees': 'Netzwerkgebühren gesamt',
    'Mento Swap Fee': 'Mento-Swap-Gebühr',
    'Celo Gas Fee': 'Celo-Gas-Gebühr',
    'Secure Enclave (TEE)': 'Sichere Enclave (TEE)',
    'Est. Arrival': 'Geschätz. Ankunft',
    '< 5 seconds': '< 5 Sekunden',
    Scheduled: 'Geplant',
    'Schedule Payment': 'Zahlung planen',
    'Confirm Transfer': 'Übertragung bestätigen',
    'Payment Scheduled!': 'Zahlung geplant!',
    'Transaction Sent!': 'Transaktion gesendet!',
    '{{amount}} {{currency}} will be sent to {{recipient}} {{frequency}} starting {{startDate}}.':
      '{{amount}} {{currency}} werden an {{recipient}} {{frequency}} ab dem {{startDate}} gesendet.',
    '{{amount}} {{currency}} is on its way to {{recipient}}.':
      '{{amount}} {{currency}} sind auf dem Weg zu {{recipient}}.',
    'View on CeloScan': 'Auf CeloScan ansehen',
    'Processing request...': 'Anfrage wird verarbeitet...',
    'Speak to CeloFlow': 'Mit CeloFlow sprechen',
    'Listening...': 'Höre zu...',
    'Type a command...': 'Befehl eingeben...',
    completed: 'abgeschlossen',
    processing: 'in Bearbeitung',
    scheduled: 'geplant',
    cancelled: 'storniert',
    failed: 'fehlgeschlagen',
    'Send 50 cUSD to Mom in Philippines': '50 cUSD an Mama auf den Philippinen senden',
    'Transfer 200 EUR to Juan in Mexico': '200 EUR an Juan in Mexiko überweisen',
    'Pay landlord 15000 KES via M-Pesa': '15000 KES Miete über M-Pesa bezahlen',
    'Send 100 cUSD to Dad every month': 'Jeden Monat 100 cUSD an Papa senden',
    'Thinking...': 'Denke...',
    'Routing...': 'Routen...',
    'Checking...': 'Überprüfe...',
    'Finding...': 'Suche...',
    'Loading...': 'Laden...',
    'Error occurred': 'Fehler aufgetreten',
    'transfer': 'Überweisung',
    'swap': 'Tausch',
    'balance': 'Guthaben',
    'contact': 'Kontakt',
    'rates': 'Kurse',
  },
  it: {
    Language: 'Lingua',
    Contacts: 'Contatti',
    'How it Works': 'Come funziona',
    Features: 'Caratteristiche',
    Developers: 'Sviluppatori',
    'Launch App': 'Avvia app',
    'SMART AGENT LIVE': 'AGENTE INTELLIGENTE LIVE',
    'Send Money Like': 'Invia denaro come',
    'You Send a': 'Tu invii un',
    Message: 'Messaggio',
    'The financial agent that turns your words into instant global transfers on the Celo blockchain. Simple, secure, and fast.':
      'L\'agente finanziario che trasforma le tue parole in trasferimenti globali istantanei sulla blockchain Celo. Semplice, sicuro e veloce.',
    'Try CeloFlow Now': 'Prova CeloFlow ora',
    'View Activity': 'Visualizza attività',
    'Trusted by 10,000+ early users': 'Affidato da oltre 10.000 utenti anticipati',
    'Just Saved': 'Risparmiato',
    '$3.50 vs Bank': '$3.50 vs Banca',
    'Built for the Real World': 'Costruito per il mondo reale',
    'CeloFlow leverages advanced blockchain infrastructure to make money move as freely as information.':
      'CeloFlow sfrutta infrastrutture blockchain avanzate per far muovere il denaro liberamente come le informazioni.',
    'Mento Protocol': 'Protocollo Mento',
    'Seamlessly swaps stablecoins (cUSD, cEUR, cREAL) with minimal slippage using decentralized stability mechanisms.':
      'Scambia senza soluzione di continuità stablecoins (cUSD, cEUR, cREAL) con slippage minimo utilizzando meccanismi di stabilità decentralizzati.',
    'TEE Security': 'Sicurezza TEE',
    'Your keys are managed in a Trusted Execution Environment. You authenticate; the enclave signs. No seed phrases to lose.':
      'Le tue chiavi sono gestite in un ambiente di esecuzione affidabile. Tu ti autentichi; l\'enclave firma. Nessuna frase seed da perdere.',
    'Gas Abstraction': 'Astrazione del gas',
    'Pay transaction fees in the same currency you send. No need to hold CELO just to pay for gas.':
      'Paga le commissioni di transazione nella stessa valuta che invii. Non c\'è bisogno di detenere CELO solo per pagare il gas.',
    'Ready to ditch the bank fees?': 'Pronto a sbarazzarti delle commissioni bancarie?',
    'Join the thousands of users saving on every remittance with CeloFlow.':
      'Unisciti alle migliaia di utenti che risparmiano su ogni rimessa con CeloFlow.',
    'Enter your email': 'Inserisci la tua email',
    'Get Early Access': 'Ottieni accesso anticipato',
    'Privacy Policy': 'Informativa sulla privacy',
    'Terms of Service': 'Termini di servizio',
    Contact: 'Contatto',
    '© 2024 CeloFlow. Built on Celo.': '© 2024 CeloFlow. Costruito su Celo.',
    Connected: 'Connesso',
    Unknown: 'Sconosciuto',
    Balance: 'Saldo',
    'Disconnect Wallet': 'Scollega wallet',
    'Connect Wallet': 'Connetti wallet',
    'Connect a Wallet': 'Connetti un wallet',
    'Connecting…': 'Connessione...',
    'Copy address': 'Copia indirizzo',
    'Smart Agent v2.1': 'Agente intelligente v2.1',
    'AI that thinks like a': 'IA che pensa come un',
    'Market Maker.': 'Market maker.',
    'CeloFlow scans decentralized exchanges (DEXs) and the Mento Protocol in real-time to find liquidity pools with the lowest slippage, ensuring your family gets the most out of every dollar sent.':
      'CeloFlow scambia decentralizzati (DEX) e il Protocollo Mento in tempo reale per trovare pool di liquidità con lo slippage più basso, garantendo che la tua famiglia ottenga il massimo da ogni dollaro inviato.',
    Slippage: 'Slippage',
    'Route Time': 'Tempo di percorso',
    'Avg. Savings': 'Risparmio medio',
    'Route Optimization': 'Ottimizzazione percorso',
    Active: 'Attivo',
    Stablecoin: 'Stablecoin',
    Local: 'Locale',
    'TEE Verification Complete': 'Verifica TEE completata',
    'Key management is handled inside a secure enclave. You never touch a private key.':
      'La gestione delle chiavi avviene all\'interno di un enclave sicuro. Non tocchi mai una chiave privata.',
    All: 'Tutti',
    Favorites: 'Preferiti',
    Blocked: 'Bloccati',
    Sort: 'Ordina',
    Name: 'Nome',
    Address: 'Indirizzo',
    Country: 'Paese',
    'Date Added': 'Data aggiunta',
    Export: 'Esporta',
    Import: 'Importa',
    Share: 'Condividi',
    'No matching contacts': 'Nessun contatto corrispondente',
    'No contacts yet': 'Ancora nessun contatto',
    'Click + to add your first contact': 'Clicca su + per aggiungere il tuo primo contatto',
    'Toggle favorite': 'Attiva/disattiva preferito',
    'Toggle blocked': 'Attiva/disattiva bloccato',
    Edit: 'Modifica',
    Delete: 'Elimina',
    'Delete Contact': 'Elimina contatto',
    'This action cannot be undone.': 'Questa azione non può essere annullata.',
    Cancel: 'Annulla',
    'Edit Contact': 'Modifica contatto',
    'New Contact': 'Nuovo contatto',
    'Name is required': 'Il nome è obbligatorio',
    'Wallet Address': 'Indirizzo wallet',
    'Address is required': 'L\'indirizzo è obbligatorio',
    Network: 'Rete',
    Phone: 'Telefono',
    Email: 'Email',
    'Invalid email format': 'Formato email non valido',
    City: 'Città',
    'Avatar URL': 'URL avatar',
    Group: 'Gruppo',
    Notes: 'Note',
    Favorite: 'Preferito',
    Update: 'Aggiorna',
    Create: 'Crea',
    'John Doe': 'Mario Rossi',
    '0x...': '0x...',
    '+1 234 567 8900': '+39 02 1234 5678',
    'john@example.com': 'mario@esempio.it',
    Manila: 'Manila',
    Philippines: 'Filippine',
    'https://...': 'https://...',
    'Family, Work, etc.': 'Famiglia, Lavoro, etc.',
    'Additional notes...': 'Note aggiuntive...',
    'Contact updated': 'Contatto aggiornato',
    'Contact created': 'Contatto creato',
    'Contact deleted': 'Contatto eliminato',
    'Exported {{count}} contacts': '{{count}} contatti esportati',
    'Import failed': 'Importazione fallita',
    'Imported {{count}} contacts': '{{count}} contatti importati',
    ', {{count}} skipped': ', {{count}} saltati',
    'No contacts to share': 'Nessun contatto da condividere',
    'Contacts copied to clipboard': 'Contatti copiati negli appunti',
    'Share failed': 'Condivisione fallita',
    'Address copied': 'Indirizzo copiato',
    '{{count}} contact': '{{count}} contatto',
    '{{count}} contacts': '{{count}} contatti',
    'Add Contact': 'Aggiungi contatto',
    'Search contacts...': 'Cerca contatti...',
    'All Groups': 'Tutti i gruppi',
    'CeloFlow Contacts': 'Contatti CeloFlow',
    "Hi! I'm CeloFlow. I can help you send money globally using the Celo blockchain. Where would you like to send money today?":
      'Ciao! Sono CeloFlow. Posso aiutarti a inviare denaro globalmente usando la blockchain Celo. Dove vorresti inviare denaro oggi?',
    'Voice input is not supported in this browser. Please use Chrome, Edge, or Safari.':
      'L\'input vocale non è supportato in questo browser. Usa Chrome, Edge o Safari.',
    'Sorry, I encountered an error connecting to the server. Please try again.':
      'Spiacente, ho riscontrato un errore durante la connessione al server. Riprova.',
    'Are you sure you want to cancel this scheduled payment?':
      'Sei sicuro di voler annullare questo pagamento programmato?',
    'CeloFlow Transaction': 'Transazione CeloFlow',
    'I just sent {{amount}} {{currency}} to {{recipient}} via CeloFlow!':
      'Ho appena inviato {{amount}} {{currency}} a {{recipient}} tramite CeloFlow!',
    'Transaction details copied to clipboard!': 'Dettagli transazione copiati negli appunti!',
    'Funds have successfully reached the recipient.': 'I fondi hanno raggiunto con successo il destinatario.',
    'Transaction is currently being confirmed on the blockchain.':
      'La transazione è attualmente in fase di conferma sulla blockchain.',
    'Payment is set to execute at a future date.': 'Il pagamento è impostato per essere eseguito in una data futura.',
    'This transaction was cancelled by the user.': 'Questa transazione è stata annullata dall\'utente.',
    'Transaction could not be completed. Please try again.':
      'La transazione non può essere completata. Riprova.',
    Online: 'Online',
    'Transaction History': 'Cronologia transazioni',
    'Recent Activity': 'Attività recente',
    'Search recipient or currency...': 'Cerca destinatario o valuta...',
    'No transactions yet.': 'Ancora nessuna transazione.',
    'No matching transactions.': 'Nessuna transazione corrispondente.',
    'Cancel Scheduled Payment': 'Annulla pagamento programmato',
    Sent: 'Inviato',
    Received: 'Ricevuto',
    '{{frequency}} starting {{startDate}}': '{{frequency}} a partire dal {{startDate}}',
    'Best Quote Found': 'Miglior preventivo trovato',
    'Saved ${{amount}}': 'Risparmiati ${{amount}}',
    'You Send': 'Tu invii',
    Receives: 'Riceve',
    'Live Real-time Rate': 'Tasso in tempo reale',
    'Estimated Fallback Rate': 'Tasso di fallback stimato',
    'Payment Schedule': 'Programma pagamento',
    'One-time': 'Una tantum',
    Daily: 'Giornaliero',
    Weekly: 'Settimanale',
    Monthly: 'Mensile',
    'Mento Protocol Status': 'Stato protocollo Mento',
    Optimal: 'Ottimale',
    'Total Network Fees': 'Commissioni di rete totali',
    'Mento Swap Fee': 'Commissione swap Mento',
    'Celo Gas Fee': 'Commissione gas Celo',
    'Secure Enclave (TEE)': 'Enclave sicuro (TEE)',
    'Est. Arrival': 'Arrivo stimato',
    '< 5 seconds': '< 5 secondi',
    Scheduled: 'Programmato',
    'Schedule Payment': 'Programma pagamento',
    'Confirm Transfer': 'Conferma trasferimento',
    'Payment Scheduled!': 'Pagamento programmato!',
    'Transaction Sent!': 'Transazione inviata!',
    '{{amount}} {{currency}} will be sent to {{recipient}} {{frequency}} starting {{startDate}}.':
      '{{amount}} {{currency}} verranno inviati a {{recipient}} {{frequency}} a partire dal {{startDate}}.',
    '{{amount}} {{currency}} is on its way to {{recipient}}.':
      '{{amount}} {{currency}} sono in viaggio verso {{recipient}}.',
    'View on CeloScan': 'Visualizza su CeloScan',
    'Processing request...': 'Elaborazione richiesta...',
    'Speak to CeloFlow': 'Parla con CeloFlow',
    'Listening...': 'Ascolto...',
    'Type a command...': 'Digita un comando...',
    completed: 'completata',
    processing: 'in elaborazione',
    scheduled: 'programmata',
    cancelled: 'annullata',
    failed: 'fallita',
    'Send 50 cUSD to Mom in Philippines': 'Invia 50 cUSD a mamma nelle Filippine',
    'Transfer 200 EUR to Juan in Mexico': 'Trasferisci 200 EUR a Juan in Messico',
    'Pay landlord 15000 KES via M-Pesa': 'Paga affitto 15000 KES via M-Pesa',
    'Send 100 cUSD to Dad every month': 'Invia 100 cUSD a papà ogni mese',
    'Thinking...': 'Pensando...',
    'Routing...': 'Instradamento...',
    'Checking...': 'Verifica...',
    'Finding...': 'Ricerca...',
    'Loading...': 'Caricamento...',
    'Error occurred': 'Errore verificato',
    'transfer': 'trasferimento',
    'swap': 'scambio',
    'balance': 'saldo',
    'contact': 'contatto',
    'rates': 'tassi',
  },
};

function isSupportedLanguage(value: string | null): value is SupportedLanguage {
  return LANGUAGE_OPTIONS.some((option) => option.code === value);
}

export function getStoredLanguage(): SupportedLanguage {
  try {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (isSupportedLanguage(stored)) return stored;
  } catch {
    // Ignore storage read errors.
  }
  return 'en';
}

export function setStoredLanguage(language: SupportedLanguage): void {
  try {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  } catch {
    // Ignore storage write errors.
  }

  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent<SupportedLanguage>(LANGUAGE_EVENT, { detail: language }));
  }
}

export function useLanguage(): readonly [SupportedLanguage, (language: SupportedLanguage) => void] {
  const [language, setLanguage] = useState<SupportedLanguage>(getStoredLanguage);

  useEffect(() => {
    const handleLanguageChange = (event: Event) => {
      const customEvent = event as CustomEvent<SupportedLanguage>;
      if (customEvent.detail) {
        setLanguage(customEvent.detail);
        return;
      }
      setLanguage(getStoredLanguage());
    };

    const handleStorage = (event: StorageEvent) => {
      if (event.key === LANGUAGE_STORAGE_KEY && isSupportedLanguage(event.newValue)) {
        setLanguage(event.newValue);
      }
    };

    window.addEventListener(LANGUAGE_EVENT, handleLanguageChange as EventListener);
    window.addEventListener('storage', handleStorage);

    return () => {
      window.removeEventListener(LANGUAGE_EVENT, handleLanguageChange as EventListener);
      window.removeEventListener('storage', handleStorage);
    };
  }, []);

  const updateLanguage = (nextLanguage: SupportedLanguage) => {
    setStoredLanguage(nextLanguage);
    setLanguage(nextLanguage);
  };

  return [language, updateLanguage] as const;
}

export function useI18n() {
  const [language, setLanguage] = useLanguage();

  const t = (text: string, params?: TranslationParams) => {
    return translate(language, text, params);
  };

  return {
    language,
    setLanguage,
    t,
  };
}
